update awesome spec to copy decidim-ub and fix alternative landing
Platoniq/decidim-recharge pull request #42
Opened 2024-09-24 16:58 UTC by HHassig

2024-09-24 17:06 UTC, HHassig commented
@fblupi, regarding the awesome specs, i have simply copied the spec file from decidim-ub

2024-09-27 08:33 UTC, fblupi requested changes, later dismissed
I checked the styles and I see some weird ones:

Search bar icon color:

<img width="273" alt="Screenshot 2024-09-27 at 10 21 39" src="https://github.com/user-attachments/assets/ab856203-b578-4d05-98ea-bce2fbbaaac0">

Links to "see all" in content blocks:

<img width="1478" alt="Screenshot 2024-09-27 at 10 23 27" src="https://github.com/user-attachments/assets/24707ffb-821a-4155-84b5-412fb550a4f3">

Day of the month color in the meetings content block:

<img width="745" alt="Screenshot 2024-09-27 at 10 24 00" src="https://github.com/user-attachments/assets/a0ca68df-d3ee-47c9-b8d5-aba874390290">

Language selector may look better with black color instead of white.

<img width="1515" alt="Screenshot 2024-09-27 at 10 24 53" src="https://github.com/user-attachments/assets/b8cb3cad-4474-4dcf-8833-aada1bc54f4b">

Section separator on main menu may look better being transparent:

<img width="442" alt="Screenshot 2024-09-27 at 10 26 42" src="https://github.com/user-attachments/assets/a11d38ac-56c7-4a11-a2e4-5ed9aec3f3d8">

When you set colours to the organization, title decorators looks weird:

<img width="309" alt="Screenshot 2024-09-27 at 10 30 56" src="https://github.com/user-attachments/assets/3e1973f3-29d9-4a35-a62f-c674dc467aa1">

Blue border color in buttons should be white, black or transparent to look better (I see them on modals and other pages, just navigate a little bit):

<img width="883" alt="Screenshot 2024-09-27 at 10 30 11" src="https://github.com/user-attachments/assets/a759cb2d-f95f-4096-b02f-17c02a1503ef">

2024-09-27 08:33 UTC, fblupi commented on app/packs/stylesheets/decidim/decidim_application.scss
> +// @import "stylesheets/recharge";
Remove this line

2024-09-27 08:33 UTC, fblupi commented on db/schema.rb
> +
Remove this. The `db/schema.rb` should be the result of running `rails db:create db:migrate`. And there is no migration to create delayed jobs table.

```suggestion
```

2025-05-20 10:46 UTC, alexrlpz approved these changes

2025-05-20 11:45 UTC, merged